"""Training plans, results, engines, and facade contracts."""

from .backend import NativeTrainingEngine
from .core import Trainer, TrainingEngine
from .checkpoint import (
    CheckpointCatalog,
    CheckpointPruneEvidence,
    CheckpointPrunePolicy,
    CheckpointRef,
    CheckpointRefStatus,
    CheckpointRetentionReason,
    CheckpointRestoreMode,
    CheckpointRestorePolicy,
    CheckpointRestoreResult,
    CheckpointResultStatus,
    CheckpointSavePolicy,
    CheckpointSaveResult,
    CheckpointSelection,
    CheckpointSelectionMode,
    CheckpointSelectionResult,
    CheckpointPruneResult,
)
from .events import (
    TrainingCallback,
    TrainingEvent,
    TrainingEventLog,
    TrainingEventPhase,
    TrainingEventSink,
    emit_training_event,
)
from .experimental import run_train
from .plan import TrainingOutputSpec, TrainingPlan
from .profiling import (
    ProfileSpanSummary,
    TrainingProfile,
    TrainingProfileRecorder,
    TrainingProfiler,
    UnavailableProfileProbe,
)
from .policies import CompilePolicy, KernelPolicy, PrecisionPolicy, PolicyStatus
from .probes import (
    DataFieldProbeSummary,
    DataProbeSummary,
    DataSampleProbeSummary,
    ModelActivationProbeSummary,
    ModelGradientProbeSummary,
    ModelHealthProbeSummary,
    ModelParameterProbeSummary,
    ModelProbeSummary,
    ModelUpdateProbeSummary,
    ProbeAggregation,
    ProbeCadence,
    ProbeCadenceMode,
    ProbeFailurePolicy,
    ProbeHookPoint,
    ProbeSelector,
    ProbeSelectorMode,
    ProbeUnavailable,
    TrainingPipelineStage,
    TrainingProbe,
    UnavailableProbeEvidence,
)
from .results import (
    ProfileSummary,
    TrainingEventSummary,
    TrainingMetricSummary,
    TrainingResult,
    TrainingStatus,
    TrainingStepSummary,
)

__all__ = [
    "ProfileSummary",
    "ProfileSpanSummary",
    "TrainingEventLog",
    "NativeTrainingEngine",
    "Trainer",
    "TrainingCallback",
    "TrainingEngine",
    "TrainingEvent",
    "TrainingEventPhase",
    "TrainingEventSummary",
    "TrainingEventSink",
    "TrainingMetricSummary",
    "TrainingOutputSpec",
    "TrainingPlan",
    "TrainingProfiler",
    "TrainingProfile",
    "TrainingProfileRecorder",
    "TrainingResult",
    "TrainingStatus",
    "TrainingStepSummary",
    "UnavailableProfileProbe",
    "CheckpointCatalog",
    "CheckpointPruneEvidence",
    "CheckpointPrunePolicy",
    "CheckpointRef",
    "CheckpointRefStatus",
    "CheckpointRetentionReason",
    "CheckpointRestoreMode",
    "CheckpointRestorePolicy",
    "CheckpointRestoreResult",
    "CheckpointResultStatus",
    "CheckpointSavePolicy",
    "CheckpointSaveResult",
    "CheckpointPruneResult",
    "CheckpointSelection",
    "CheckpointSelectionMode",
    "CheckpointSelectionResult",
    "CompilePolicy",
    "KernelPolicy",
    "PrecisionPolicy",
    "PolicyStatus",
    "DataFieldProbeSummary",
    "DataProbeSummary",
    "DataSampleProbeSummary",
    "ModelActivationProbeSummary",
    "ModelGradientProbeSummary",
    "ModelHealthProbeSummary",
    "ModelParameterProbeSummary",
    "ModelProbeSummary",
    "ModelUpdateProbeSummary",
    "ProbeAggregation",
    "ProbeCadence",
    "ProbeCadenceMode",
    "ProbeFailurePolicy",
    "ProbeHookPoint",
    "ProbeSelector",
    "ProbeSelectorMode",
    "ProbeUnavailable",
    "TrainingPipelineStage",
    "TrainingProbe",
    "UnavailableProbeEvidence",
    "emit_training_event",
    "run_train",
]
